- name: Create Server
  hosts: localhost
  gather_facts: False

  tasks:

  - name: Get the variables
    include_vars:
      dir: vars/

  - name: Create EC2 Instance
    ec2:
      key_name: "{{ aws_ssh_key }}"
      region: "{{ aws_region }}"
      instance_type: "{{ aws_instance_type }}"
      user_data: |
                 #!/bin/sh
                 echo "{{ ansible_ssh_pub }}" > /root/.ssh/authorized_keys
                 apt install -y python python-simplejson
      image: "{{ aws_instance_ami }}"
      wait: false
      count: "{{ item.count }}"
      group_id: "{{ aws_security_groups }}"
      vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
      instance_tags: '{"Name":"{{ item.role }}","Role":"{{ item.role }}"}'
    loop:
      - { role: 'AWX Server', count: 1 }
      #- { role: 'Webserver', count: 2 }
      #- { role: 'Reverse Proxy', count: 2 }


- name: Assign Elastic IP
  hosts: tag_Role_AWX_Server
  gather_facts: False

  tasks:
  - name: Assign Elastic IP
    ec2_eip:
      device_id: {{ ec2_id }}
      #ip: 18.185.233.18
      ip: 3.120.1.51

  #- name: Get Instance ID
  #  debug:
  #    msg: "Instance ID: {{ ec2_id }}"
